Repository shippingpark/Cookies-DevLab, pull requests merged in 2024-11, with the labels that each got.

#15 [Mission/#3-IO] 2일차 미션
  IODevLabApp/IODevLabApp.xcodeproj/project.pbxproj
  IODevLabApp/IODevLabApp/Base.lproj/Main.storyboard
  IODevLabApp/IODevLabApp/SpendTableViewCell.swift
  IODevLabApp/IODevLabApp/ViewController.swift
Labels: Mission Clear, 이오

#14 [Mission/#3- Bono] 2일차 미션
  BonoDevLabApp/BonoDevLabApp.xcodeproj/project.xcworkspace/xcuserdata/bono.xcuserdatad/UserInterfaceState.xcuserstate
  BonoDevLabApp/BonoDevLabApp/Base.lproj/Main.storyboard
Labels: Mission Clear, 보노

#13 [Mission/#3-Tina] 2일차 미션
  TinaDevLabApp/TinaDevLabApp.xcodeproj/project.pbxproj
  TinaDevLabApp/TinaDevLabApp/Base.lproj/Main.storyboard
  TinaDevLabApp/TinaDevLabApp/CustomeCell.swift
  TinaDevLabApp/TinaDevLabApp/ViewController.swift
Labels: Mission Clear, 티나

#12 [Mission/#3-Rochelle] 2일차 미션
  RochelleDevLabApp/RochelleDevLabApp.xcodeproj/project.pbxproj
  RochelleDevLabApp/RochelleDevLabApp.xcodeproj/xcshareddata/xcschemes/RochelleDevLabApp.xcscheme
  RochelleDevLabApp/RochelleDevLabApp/Base.lproj/Main.storyboard
  RochelleDevLabApp/RochelleDevLabApp/ResultTableViewCell.swift
  RochelleDevLabApp/RochelleDevLabApp/ViewController.swift
Labels: Mission Clear, 몽쉘

#16 [Mission/#4-Rochelle] 3일차 미션
  RochelleDevLabApp/RochelleDevLabApp.xcodeproj/project.pbxproj
  RochelleDevLabApp/RochelleDevLabApp/Base.lproj/Main.storyboard
  RochelleDevLabApp/RochelleDevLabApp/ExpenseCell.swift
  RochelleDevLabApp/RochelleDevLabApp/Info.plist
  RochelleDevLabApp/RochelleDevLabApp/ResultTableViewCell.swift
  RochelleDevLabApp/RochelleDevLabApp/SceneDelegate.swift
  RochelleDevLabApp/RochelleDevLabApp/ViewController.swift
Labels: OnGoing, 몽쉘

#17 [Mission/#4-IO] 3일차 미션
  IODevLabApp/IODevLabApp.xcodeproj/project.pbxproj
  IODevLabApp/IODevLabApp/Base.lproj/Main.storyboard
  IODevLabApp/IODevLabApp/ObjectSetter.swift
  IODevLabApp/IODevLabApp/SceneDelegate.swift
  IODevLabApp/IODevLabApp/SpendRecordTableViewCell.swift
  IODevLabApp/IODevLabApp/SpendRecordViewController.swift
  IODevLabApp/IODevLabApp/ViewController.swift
Labels: OnGoing, 이오

#18 [Mission/#4-Tina] 3일차 미션
  TinaDevLabApp/TinaDevLabApp.xcodeproj/project.pbxproj
  TinaDevLabApp/TinaDevLabApp/Base.lproj/Main.storyboard
  TinaDevLabApp/TinaDevLabApp/Main.storyboard
  TinaDevLabApp/TinaDevLabApp/SpendTableViewCell.swift
  TinaDevLabApp/TinaDevLabApp/ViewController.swift
Labels: OnGoing, 티나

#20 [Mission/#5-Tina] 4일차 미션
  TinaDevLabApp/TinaDevLabApp.xcodeproj/project.pbxproj
  TinaDevLabApp/TinaDevLabApp/SpendTableViewCell.swift
  TinaDevLabApp/TinaDevLabApp/SwiftUIView.swift
  TinaDevLabApp/TinaDevLabApp/ViewController.swift
Labels: OnGoing, 티나

#21 [Mission/#5-Rochelle] 4일차 미션
  RochelleDevLabApp/RochelleDevLabApp/ExpenseCell.swift
  RochelleDevLabApp/RochelleDevLabApp/ViewController.swift
Labels: OnGoing, 몽쉘

#24 [Mission/#6-IO] 5일차 미션
  IODevLabApp/IODevLabApp.xcodeproj/project.pbxproj
  IODevLabApp/IODevLabApp.xcodeproj/xcshareddata/xcschemes/IODevLabApp.xcscheme
  IODevLabApp/IODevLabApp/LatestSpendView.swift
  IODevLabApp/IODevLabApp/SpendRecordTableViewCell.swift
  IODevLabApp/IODevLabApp/SpendRecordViewController.swift
  IODevLabApp/IODevLabAppTests/IODevLabAppTests.swift
  IODevLabApp/IODevLabAppTests/NumberFormatterTests.swift
Labels: OnGoing, 이오

#23 [Mission/#6-Tina] 5일차 미션
  TinaDevLabApp/TinaDevLabApp/SpendTableViewCell.swift
  TinaDevLabApp/TinaDevLabApp/ViewController.swift
Labels: OnGoing, 티나

#22 [Mission/#6-Rochelle] 5일차 미션
  RochelleDevLabApp/RochelleDevLabApp.xcodeproj/project.pbxproj
  RochelleDevLabApp/RochelleDevLabApp/ExpenseCell.swift
  RochelleDevLabApp/RochelleDevLabApp/ExpenseViewModel.swift
  RochelleDevLabApp/RochelleDevLabApp/SwiftUIView.swift
  RochelleDevLabApp/RochelleDevLabApp/ViewController.swift
Labels: OnGoing, 몽쉘
