Repository shippingpark/Cookies-DevLab, pull requests merged in 2024-10, with the labels that each got.

#7 [Mission/#2-Bono] 1일차 미션
  BonoDevLabApp/.DS_Store
  BonoDevLabApp/BonoDevLabApp.xcodeproj/project.pbxproj
  BonoDevLabApp/BonoDevLabApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  BonoDevLabApp/BonoDevLabApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  BonoDevLabApp/BonoDevLabApp.xcodeproj/project.xcworkspace/xcuserdata/bono.xcuserdatad/UserInterfaceState.xcuserstate
  BonoDevLabApp/BonoDevLabApp.xcodeproj/xcuserdata/bono.xcuserdatad/xcschemes/xcschememanagement.plist
  BonoDevLabApp/BonoDevLabApp/AppDelegate.swift
  BonoDevLabApp/BonoDevLabApp/Assets.xcassets/AccentColor.colorset/Contents.json
  BonoDevLabApp/BonoDevLabApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  BonoDevLabApp/BonoDevLabApp/Assets.xcassets/Contents.json
  BonoDevLabApp/BonoDevLabApp/Base.lproj/LaunchScreen.storyboard
  BonoDevLabApp/BonoDevLabApp/Base.lproj/Main.storyboard
  BonoDevLabApp/BonoDevLabApp/Info.plist
  BonoDevLabApp/BonoDevLabApp/SceneDelegate.swift
  BonoDevLabApp/BonoDevLabApp/ViewController.swift
  BonoDevLabApp/BonoDevLabAppTests/BonoDevLabAppTests.swift
  BonoDevLabApp/BonoDevLabAppUITests/BonoDevLabAppUITests.swift
  BonoDevLabApp/BonoDevLabAppUITests/BonoDevLabAppUITestsLaunchTests.swift
Labels: Mission Clear, 보노

#8 [Mission/#2-IO] 1일차 미션
  IODevLabApp/IODevLabApp.xcodeproj/project.pbxproj
  IODevLabApp/IODevLabApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  IODevLabApp/IODevLabApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  IODevLabApp/IODevLabApp/AppDelegate.swift
  IODevLabApp/IODevLabApp/Assets.xcassets/AccentColor.colorset/Contents.json
  IODevLabApp/IODevLabApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  IODevLabApp/IODevLabApp/Assets.xcassets/Contents.json
  IODevLabApp/IODevLabApp/Base.lproj/LaunchScreen.storyboard
  IODevLabApp/IODevLabApp/Base.lproj/Main.storyboard
  IODevLabApp/IODevLabApp/Info.plist
  IODevLabApp/IODevLabApp/SceneDelegate.swift
  IODevLabApp/IODevLabApp/ViewController.swift
  IODevLabApp/IODevLabAppTests/IODevLabAppTests.swift
  IODevLabApp/IODevLabAppUITests/IODevLabAppUITests.swift
  IODevLabApp/IODevLabAppUITests/IODevLabAppUITestsLaunchTests.swift
Labels: Mission Clear, 이오

#9 [Mission/#2-Rochelle] 1일차 미션
  RochelleDevLabApp/RochelleDevLabApp.xcodeproj/project.pbxproj
  RochelleDevLabApp/RochelleDevLabApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  RochelleDevLabApp/RochelleDevLabApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  RochelleDevLabApp/RochelleDevLabApp/AppDelegate.swift
  RochelleDevLabApp/RochelleDevLabApp/Assets.xcassets/AccentColor.colorset/Contents.json
  RochelleDevLabApp/RochelleDevLabApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  RochelleDevLabApp/RochelleDevLabApp/Assets.xcassets/Contents.json
  RochelleDevLabApp/RochelleDevLabApp/Base.lproj/LaunchScreen.storyboard
  RochelleDevLabApp/RochelleDevLabApp/Base.lproj/Main.storyboard
  RochelleDevLabApp/RochelleDevLabApp/Info.plist
  RochelleDevLabApp/RochelleDevLabApp/SceneDelegate.swift
  RochelleDevLabApp/RochelleDevLabApp/ViewController.swift
  RochelleDevLabApp/RochelleDevLabAppTests/RochelleDevLabAppTests.swift
  RochelleDevLabApp/RochelleDevLabAppUITests/RochelleDevLabAppUITests.swift
  RochelleDevLabApp/RochelleDevLabAppUITests/RochelleDevLabAppUITestsLaunchTests.swift
Labels: Mission Clear, 몽쉘

#10 [Mission/#2-Tina] 1일차 미션
  TinaDevLabApp/TinaDevLabApp.xcodeproj/project.pbxproj
  TinaDevLabApp/TinaDevLabApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  TinaDevLabApp/TinaDevLabApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  TinaDevLabApp/TinaDevLabApp/AppDelegate.swift
  TinaDevLabApp/TinaDevLabApp/Assets.xcassets/AccentColor.colorset/Contents.json
  TinaDevLabApp/TinaDevLabApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  TinaDevLabApp/TinaDevLabApp/Assets.xcassets/Contents.json
  TinaDevLabApp/TinaDevLabApp/Base.lproj/LaunchScreen.storyboard
  TinaDevLabApp/TinaDevLabApp/Base.lproj/Main.storyboard
  TinaDevLabApp/TinaDevLabApp/Info.plist
  TinaDevLabApp/TinaDevLabApp/SceneDelegate.swift
  TinaDevLabApp/TinaDevLabApp/ViewController.swift
  TinaDevLabApp/TinaDevLabAppTests/TinaDevLabAppTests.swift
  TinaDevLabApp/TinaDevLabAppUITests/TinaDevLabAppUITests.swift
  TinaDevLabApp/TinaDevLabAppUITests/TinaDevLabAppUITestsLaunchTests.swift
Labels: Mission Clear, 티나
